language: csharp
mono: none
dotnet: 4.6.1

addons:
  sonarcloud:
    organization: "nabilalamgir-github"

before_install:
- bash ./tools/travis-ci-install-sonar.sh

install:
- dotnet restore src

script:
 - bash ./tools/travis-ci-build.sh
